### ISSUE TITLE
can this code work for live camera mode ?

### ISSUE THREAD

**Issue by cheylong** [geliuhao/CVPR2016_HandPoseEstimation#1]
Thanks for share your code, I have several for the "Fusion" projection.
 I use one .oni file as input ,and put a red wristband as mark to get hand ROI,  but when I convert the depth data(the depht value is 700mm) to the heatmap , the predict results are all same as one finger.

![qq 20160822123315](https://cloud.githubusercontent.com/assets/17828622/17843778/a0888d44-6864-11e6-9dbc-d5402a3fb92e.png)

and my oni file are Recorded by PrimeSense Carmine 1.08 (240*320 30FPS)

**Comment by geliuhao** [comment]
Yes, but you need to modify the code to make the input as the "oni" file. For this released code, the input is a binary file in the MSRA dataset (http://research.microsoft.com/en-us/um/people/yichenw/handpose/cvpr15_MSRAHandGestureDB.zip). You can check our paper for details:
http://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Ge_Robust_3D_Hand_CVPR_2016_paper.pdf

**Comment by cheylong** [comment]
OK，thanks
