### ISSUE TITLE
Can I take this dataset?

### ISSUE THREAD

**Issue by yeon3683** [geliuhao/CVPR2016_HandPoseEstimation#3]
Thank you for sharing your code. I want to test your code before starting my similar project.
But I can't find the dataset at here : 
http://research.microsoft.com/en-us/um/people/yichenw/handpose/cvpr15_MSRAHandGestureDB.zip

I think that link is gone. so I ran your code without dataset, console give me : 
Could not open joint.txt file

Then, can you give me this dataset or another link?

Thanks!

**Comment by geliuhao** [comment]
Thank you for your attention. The dataset cannot download from the link now. I suggest you to contact with Dr. Wei Yicheng who released the dataset.

**Comment by geliuhao** [comment]
By Dr. Wei Yichen's authorization, I upload the MSRA hand pose dataset in this link: https://www.dropbox.com/s/bmx2w0zbnyghtp7/cvpr15_MSRAHandGestureDB.zip?dl=0

Please cite "Xiao Sun, Yichen Wei, Shuang Liang, Xiaoou Tang and Jian Sun. Cascaded Hand Pose Regression. IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2015", if you use this database.
