### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by qdesmedt** [geliuhao/CVPR2016_HandPoseEstimation#4]
I would like to use your code for research purpose and comparison experiments.

Do you yet provide the dataset ? It cannot be downloaded from your link.

Thanks a lot for sharing your code.

**Comment by geliuhao** [comment]
Thank you for your attention. I will send an email to the authors who released the dataset. If they authorize me to release the dataset, I will release it on Github. Hope for your understanding. Thank you.

**Comment by geliuhao** [comment]
By Dr. Wei Yichen's authorization, I upload the MSRA hand pose dataset in this link: https://www.dropbox.com/s/bmx2w0zbnyghtp7/cvpr15_MSRAHandGestureDB.zip?dl=0

Please cite "Xiao Sun, Yichen Wei, Shuang Liang, Xiaoou Tang and Jian Sun. Cascaded Hand Pose Regression. IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2015", if you use this database.
